net_sched: Mark qcb as __maybe_unused
To work around a Clang bug, WireGuard turns BUILD_BUG_ON into a no-op.
As a result, Clang warns that qcb is unused:

../include/net/sch_generic.h:251:23: error: unused variable 'qcb'
[-Werror,-Wunused-variable]
        struct qdisc_skb_cb *qcb;
                             ^
1 error generated.

Mark qcb as __maybe_unused so that Clang no longer warns.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>